name: Build & Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Cache Dependencies
        id: cache-key
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        run: npm ci

      - name: Install Nx CLI Globally
        run: npm install -g nx

  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ needs.setup.outputs.cache-key }}

      - name: Install Nx CLI Globally
        run: npm install -g nx

      - name: Run Tests
        run: npx nx run-many --target=test --all --configuration=ci

  build-mill-shop:
    runs-on: ubuntu-latest
    needs: [setup, test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ needs.setup.outputs.cache-key }}

      - name: Install Nx CLI Globally
        run: npm install -g nx

      - name: Build Angular App
        run: npx nx build mill-shop --configuration=production

      - name: Deploy Angular App to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/apps/mill-shop
          target-folder: .
          token: ${{ secrets.GH_TOKEN }}
          clean: false

  build-storybook:
    runs-on: ubuntu-latest
    needs: [setup, test]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ needs.setup.outputs.cache-key }}

      - name: Install Nx CLI Globally
        run: npm install -g nx

      - name: Build Storybook
        run: npx nx run design-system:build-storybook

      - name: Deploy Storybook to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist/storybook/design-system
          target-folder: storybook
          token: ${{ secrets.GH_TOKEN }}
          clean: false
